### ISSUE TITLE
[BUG] detection reentrance on specific conditions

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/Luos#107]
**Describe the bug**
It's possible to have detection reentrance if user make the launch of a detection on an event in msg_handler triggered by a localhost service.
For example a button board with a button driver service and an App running a detection on push.
When you push the button detection is launched from message_handler, but it's possible than the detection run Luos_Loop(). If Your button service send another information about the push of the button it could re-call the detection in the middle on detection.
Witch is bad...

**Network configuration**
To reproduce it you probably need to have quite a large network making the detection wait and call Luos_Loop

**Additional context**
This bug have been hidden in the detection button app from the led_strip Demo

**Comment by Salem-Luos** [comment]
Fix in Luos 2.1.0
