### ISSUE TITLE
[BUG] Big network issue

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/Luos#108]
**Describe the bug**
When there is a lot of nodes on a network during the detection we copy the routing table in each node.
The first nodes that get this routing table are ready to send things but not the other. Potentially messages send during those copies can be ignored because routing table is not already up to date in all the nodes.
This could lead to a change in the behavior depending on the position of the nodes from the detector.

**Network configuration**
Quite a big one with a lot of nodes.
And we need to have the application sending things like configuration just after the detection.

**Additional context**
This bug has been hidden by delaying configurations send on our demos (bike alarm and led_strip)

**Comment by Salem-Luos** [comment]
Fixed in 2.1.0
