### ISSUE TITLE
[BUG] Compilation error when using platformio libraries on local computer

### ISSUE THREAD

**Issue by JeromeGalan** [Luos-io/Luos#128]
**Describe the bug**

Context :
- OS : Windows.
- "PLATFORMIO_LIB_EXTRA_DIR" environment variable points to a local directory.
- This local directory includes many libraries and projects. For example, it can be your local workspace directory with many differents projects, even if there are not Luos related.

When compiling a project, PlatformIO  scans all directories pointed by PLATFORMIO_LIB_EXTRA_DIR.
Then, PlatformIO tries to compile all directories. Maybe it believes those dir are "libraries"...
So, depending of your local directory structure, the compilation fails.

**How to reproduce the bug**
See context in above section.

**Suggestions**
- Try to find a clean fix (maybe in platformio.ini ?).
- If it's not possible, we'll have to add a specific troubleshooting chapter in the Luos documentation.

**Comment by Salem-Luos** [comment]
It's a platformio problem
