### ISSUE TITLE
[NEW FEATURE] Luos_SendMsgTimeStamp

### ISSUE THREAD

**Issue by Salem-Luos** [Luos-io/Luos#167]
**What feature would you like to be included in Luos?**

Luos does not initialize field of the msg_t structure when a msg variable is create.

In some case, when you don't want to send with timestamps, the field may have the wrong value and will be miss interpreate by the receiver.

we need 2 fonction : 
Luos_SendMsg that force the field to 0
Luos_SendMsgTimeStamp that force the field to 1 

Luos_SendMsgTimeStamp function will concatenate the 2 part of code (encode timestamps and send)

**Comment by ncros3** [comment]
A commit takes this issue in #149
