### ISSUE TITLE
[BUG] GitHub Button on Navbar Not Functional on Landing Page

### ISSUE THREAD

**Issue by Sukhendu2002** [Luos-io/luos#240]
**Describe the bug**
On the landing page's navbar, the GitHub button is not functioning as expected.

**How to reproduce the bug**

1. Open a web browser.
2. Navigate to the landing page of the application.
3. Locate the GitHub button in the navbar.
4. Attempt to click on the GitHub button.

**Additional context**
NA

**Comment by Sukhendu2002** [comment]
Can I work on this issue

**Comment by nicolas-rabault** [comment]
Hi @Sukhendu2002  thank you for spotting this.
Of course, you can work on this issue, please feel free to make a pull request.
